name: tyf
dataset: mysam/tyf
devices:
- 1
actions:
# training tokenizer or loading it if trained
- id: llama_tokenizer
  type: train_load_tokenizer
  kind: auto
  path: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/models--meta-llama--Llama-3.2-1B/snapshots/4e20de362430cd3b72f300e6b0f18e50e7166e08
  vocab_size: 128256
  status: always

- id: llama_rl_reward
  type: train_reward_model
  base_model: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/models--meta-llama--Llama-3.2-1B/snapshots/4e20de362430cd3b72f300e6b0f18e50e7166e08
  tokenizer_id: llama_tokenizer
  output_dir: model/reward/tyf
  batch_size: 2
  status: pending

- id: policy_model
  type: train_policy_model
  reward_model: model/reward/tyf
  ref_policy_model: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/models--meta-llama--Llama-3.2-1B/snapshots/4e20de362430cd3b72f300e6b0f18e50e7166e08
  policy_model: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/models--meta-llama--Llama-3.2-1B/snapshots/4e20de362430cd3b72f300e6b0f18e50e7166e08
  tokenizer_id: llama_tokenizer
  output_dir: model/policy/tyf
  status: pending