name: maajim
dataset: mysam/masael_chat
devices:
- 1
actions:
# loading full dataset
- id: load_dataset
  type: load_dataset
  shuffle: true
  status: always
# training tokenizer or loading it if trained
- id: llama_tokenizer
  type: train_load_tokenizer
  kind: auto
  path: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/mysam/oryx-2.0-1B-Base
  vocab_size: 32000
  status: always

# sft-training on the model trained based on the 10 samples dataset
- id: sft_training
  type: sft
  pretrained_model_kind: auto
  pretrained_model_ckpt: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/mysam/oryx-2.0-1B-Base-Maajim-3
  tokenizer_id: llama_tokenizer
  sample_size: 0.90
  path: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/mysam/oryx-2.0-1B-Instruct-Maajim-3

  # this is sft config
  sft_config:
    seed: 42
    max_steps: -1
    save_strategy: no
    num_train_epochs: 3
    max_seq_length: 8192
    save_total_limit:
    learning_rate: 2.0e-06
    logging_strategy: steps
    lr_scheduler_type: cosine
    output_dir: /home/jalalirs/Documents/code/arabi/maknaz/maknaz_/model/mysam/oryx-2.0-1B-Instruct-Maajim-3
    per_device_eval_batch_size: 1
    per_device_train_batch_size: 1
    logging_steps: 10
  # lora_config:
  #   r: 16
  #   lora_alpha: 32
  #   lora_dropout: 0.05
  #   target_modules: "all-linear"
  #   modules_to_save: ["lm_head", "embed_token"]
  #   task_type: "CAUSAL_LM"
  status: always
